import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: { backgroundColor: '#FFF', padding: 16, borderRadius: 20, marginBottom: 12, flexDirection: 'row', borderWidth: 1, borderColor: '#F1F5F9' },
  content: { flex: 1 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between' },
  idContainer: { flexDirection: 'row', gap: 8 },
  idText: { fontSize: 10, fontFamily: 'PoppinsSemiBold', color: '#000' },
  methodBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  methodBadgeText: { fontSize: 8, fontFamily: 'PoppinsBold' },
  cashierBadge: { flexDirection: 'row', gap: 4, alignItems: 'center', backgroundColor: '#F8FAFC', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
  cashierName: { fontSize: 9, fontFamily: 'PoppinsSemiBold', color: '#64748B' },
  dateText: { fontSize: 11, fontFamily: 'PoppinsMedium', color: '#64748B', marginVertical: 6 },
  footerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  totalText: { fontSize: 16, fontFamily: 'PoppinsBold', color: '#000' },
  itemBadge: { flexDirection: 'row', gap: 4, alignItems: 'center', backgroundColor: '#F8FAFC', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
  itemCount: { fontSize: 11, fontFamily: 'PoppinsSemiBold', color: '#64748B' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(15,23,42,0.6)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#FFF', borderTopLeftRadius: 32, borderTopRightRadius: 32, maxHeight: '90%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', padding: 24 },
  modalTitle: { fontSize: 18, fontFamily: 'PoppinsBold' },
  closeBtn: { backgroundColor: '#F1F5F9', padding: 8, borderRadius: 12 },
  scrollContent: { paddingBottom: 40 },
  modalBody: { padding: 24 },
  infoCard: { backgroundColor: '#F8FAFC', borderRadius: 20, padding: 16, marginBottom: 24 },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between' },
  infoLabel: { color: '#64748B' },
  infoValueContainer: { flexDirection: 'row', gap: 6 },
  infoValue: { fontFamily: 'PoppinsSemiBold' },
  divider: { height: 1, backgroundColor: '#E2E8F0', marginVertical: 8 },
  sectionTitle: { fontSize: 16, fontFamily: 'PoppinsBold', marginBottom: 12 },
  itemsContainer: { marginBottom: 20 },
  productCard: { backgroundColor: '#FFF', borderRadius: 16, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: '#F1F5F9' },
  productHeader: { flexDirection: 'row', marginBottom: 8 },
  productIndex: { fontFamily: 'PoppinsBold', color: '#64748B', marginRight: 6 },
  productName: { fontFamily: 'PoppinsSemiBold', flex: 1 },
  productDetailRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  productDetailLabel: { fontSize: 12, color: '#64748B' },
  productDetailValue: { fontSize: 12, fontFamily: 'PoppinsMedium' },
  productSubtotalRow: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#E5E7EB', paddingTop: 8 },
  productSubtotalLabel: { fontFamily: 'PoppinsSemiBold' },
  productSubtotalValue: { fontFamily: 'PoppinsBold' },
  paymentSummaryCard: { borderRadius: 24, padding: 20 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between' },
  summaryLabel: { color: 'rgba(255,255,255,0.8)' },
  summaryValue: { color: '#FFF', fontFamily: 'PoppinsSemiBold' },
  summaryValueBig: { color: '#FFF', fontSize: 22, fontFamily: 'PoppinsBold' },
  dividerLight: { height: 1, backgroundColor: 'rgba(255,255,255,0.15)', marginVertical: 10 },
});